name: test/lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git code download
        uses: actions/checkout@v3

      - name: installing dependcies
        run: npm ci

      - name: lint 
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Git code download
        uses: actions/checkout@v3

      - name: installing dependcies
        run: npm install

      - name: test  
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint,test]
    steps:
      - name: Git code download
        uses: actions/checkout@v3

      - name: installing dependcies
        run: npm install

      - name: build  
        run: npm build
            
      - name: deploying status
        run: echo "Deploying application"

